Feat/board
Bamdoliro/Gati-server pull request #66
Opened 2022-06-12 07:32 UTC by leekyukin

## 📄 Summary
> test

<br>

## 🔨 Tasks
- 한번 정리 하고 갸야될것 같음..

<br>

## 🙋🏻 Halmal

2022-06-12 13:15 UTC, gimhanul reviewed
CI Failed 확인해주세여

2022-06-12 13:15 UTC, gimhanul commented on src/test/java/com/bamdoliro/gati/domain/board/service/BoardServiceTest.java
> +    public void givenBoard_whenSavePost_thenCreateBoard() throws Exception {
Exception 던지는 이유가 따로 있나요?

2022-06-12 13:15 UTC, gimhanul commented on src/test/java/com/bamdoliro/gati/domain/board/service/BoardServiceTest.java
> +        assertEquals(1, savedBoard.getCommunity().getId());
이렇게 id 관련한 코드가 말이 안 되는 이유는... 위에서 board, community, user 생성할 때 id값을 따로 주지 않았기 때문입니다. 따라서 현재 각 object에는 id값이 null로 들어있습니다.
저는 이를 무시하고 테스트를 진행하는데, 이를 해결하려면 entity에 `@AllArgsConstructor`를 붙이는 방법 쯤이 있겠네요.

2022-06-12 13:15 UTC, gimhanul commented on src/test/java/com/bamdoliro/gati/domain/board/service/BoardServiceTest.java
> +        assertEquals(1, savedBoard.getCommunity().getId());
id 관련된 코드 무시할 건지 아님 해결할 건지 답변 남겨주세용. -> 해결할 거면 저도 참여하려고~

2022-06-12 13:15 UTC, gimhanul commented on src/test/java/com/bamdoliro/gati/domain/board/service/BoardServiceTest.java
> +        assertEquals("내영내영냉용내용내용내용내용ㄴ애욘애요내요랜ㅇ래내요래ㅛ내욘료ㅐㄴ요ㅐ료냐요래", savedBoard.getContent());
요런 친구들은 이제 request에서 뽑아오면 좋을 거 같아요

2022-06-12 13:15 UTC, gimhanul commented on src/test/java/com/bamdoliro/gati/domain/board/service/BoardServiceTest.java
> +        verify(boardRepository, times(1)).save(boardCaptor.capture()); // 여기서 오류남 확인 바람
무슨 오류 나는지 구체적으로 말해주세욤

2022-06-13 07:09 UTC, leekyukin commented on src/test/java/com/bamdoliro/gati/domain/board/service/BoardServiceTest.java
> +    public void givenBoard_whenSavePost_thenCreateBoard() throws Exception {
강의에서 그렇게 하더라고요.
지우는게 나을까요?

2022-06-13 08:25 UTC, leekyukin commented on src/test/java/com/bamdoliro/gati/domain/board/service/BoardServiceTest.java
> +        assertEquals(1, savedBoard.getCommunity().getId());
이해가 가버렸네요.
무시해야 코드가 깔끔하겠네요

2022-06-13 08:26 UTC, leekyukin commented on src/test/java/com/bamdoliro/gati/domain/board/service/BoardServiceTest.java
> +        assertEquals("내영내영냉용내용내용내용내용ㄴ애욘애요내요랜ㅇ래내요래ㅛ내욘료ㅐㄴ요ㅐ료냐요래", savedBoard.getContent());
요런 친구라고 하면 assertEuals()의 첫번째 파라미터를 말씀하시는 건가요

2022-06-13 11:28 UTC, gimhanul commented on src/test/java/com/bamdoliro/gati/domain/board/service/BoardServiceTest.java
> +        assertEquals("내영내영냉용내용내용내용내용ㄴ애욘애요내요랜ㅇ래내요래ㅛ내욘료ㅐㄴ요ㅐ료냐요래", savedBoard.getContent());
넹

2022-06-13 11:29 UTC, gimhanul commented on src/test/java/com/bamdoliro/gati/domain/board/service/BoardServiceTest.java
> +    public void givenBoard_whenSavePost_thenCreateBoard() throws Exception {
넴

2022-06-16 08:35 UTC, gimhanul commented on src/test/java/com/bamdoliro/gati/domain/board/service/BoardServiceTest.java
> +        ArgumentCaptor<Long> longCaptor = ArgumentCaptor.forClass(Long.class);
안 쓰는 captor 삭제해 주세요!

2022-06-16 08:36 UTC, gimhanul commented on src/test/java/com/bamdoliro/gati/domain/board/service/BoardServiceTest.java
> +        verify(communityFacade, times(1)).findCommunityById(longCaptor.capture());
마찬가지로 여기서는 capture 안 해줘도 됩니다.

2022-06-16 08:40 UTC, gimhanul requested changes
긋입니다 👍

2022-06-21 10:12 UTC, merged